import { Product } from "../interface/interface-const";

export const books: Product[] = [
  {
		bookId:'book1',
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/pandora.jpg',
		product:'Pandora',
		description:'A pure pleasure of a novel set in Georgian London, where the discovery of a mysterious ancient Greek vase sets in motion conspiracies, revelations and romance.',
		recommendations:'Perfect for readers who loved The Binding and The Essex Serpent.',
		story:"London, 1799. Dora Blake is an aspiring jewellery artist who lives with her uncle in what used to be her parents' famed shop of antiquities. When a mysterious Greek vase is delivered, Dora is intrigued by her uncle's suspicious behaviour and enlists the help of Edward Lawrence, a young antiquarian scholar. Edward sees the ancient vase as key to unlocking his academic future. Dora sees it as a chance to restore the shop to its former glory, and to escape her nefarious uncle But what Edward discovers about the vase has Dora questioning everything she has believed about her life, her family, and the world as she knows it. As Dora uncovers the truth she starts to realise that some mysteries are buried, and some doors are locked, for a reason. Gorgeously atmospheric and deliciously page-turning, Pandora is a story of secrets and deception, love and fulfilment, fate and hope",
		author:'Susan Stokes-Chapman',
		category:'Novels',
		cost:14.99,
		count:4
	},
	{
		bookId:'book2',
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/Free%20Love.jpg',
		product:'Free Love',
		description:"Tessa Hadley recruits admirers with each book. She writes with authority, and with delicacy: she explores nuance, but speaks plainly; she is one of those writers a reader trusts.",
		recommendations:"From the bestselling author of Late in the Day and The Past comes a compulsive new novel about one woman's sexual and intellectual awakening in 1960s London",
		story:"1967. While London comes alive with the new youth revolution, the suburban Fischer family seems to belong to an older world of conventional stability: pretty, dutiful homemaker Phyllis is married to Roger, a devoted father with a career in the Foreign Office. Their children are Colette, a bookish teenager, and Hugh, the golden boy.But when the twenty-something son of an old friend pays the Fischers a visit one hot summer evening, and kisses Phyllis in the dark garden after dinner, something in her catches fire. Newly awake to the world, Phyllis makes a choice that defies all expectations of her as a wife and a mother. Nothing in these ordinary lives is so ordinary after all, it turns out, as the family's upheaval mirrors the dramatic transformation of the society around them.With scalpel-sharp insight, Tessa Hadley explores her characters' inner worlds, laying bare their fears and longings. Daring and sensual, Free Love is an irresistible exploration of romantic love, sexual freedom and living out the truest and most meaningful version of our selves - a novel that showcases Hadley's unrivaled ability to 'put on paper a consciousness so visceral, so fully realized, it heightens and expands your own' (Lily King, author of Euphoria)",
		author:'Tessa Hadley',
		category:'Novels',
		cost:14.99,
		count:2
	},
	{
		bookId:'book3',
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/The%20Ticket%20Collector%20from%20Belarus.jpg',
		product:'The Ticket Collector from Belarus',
		description:"'Brilliantly gripping' Sunday Times; 'Compelling' Daily Mail; 'Heart-rending' Sunday Telegraph; 'Excellent' The Times; 'Engrossing' Independent",
		recommendations:"The UK's only war crimes trial took place in 1999 and had its origins in the horrors of the Holocaust, but only now in The Ticket Collector from Belarus? can the full story be told",
		story:"The Ticket Collector from Belarus tells the remarkable story of two interwoven journeys. Ben-Zion Blustein and Andrei Sawoniuk were childhood friends in 1930s Domachevo, a holiday and health resort in what is now Belarus. During the events that followed the Nazi invasion in 1941, they became the bitterest of enemies. After the war, Ben-Zion made his way to Israel, and ‘Andrusha the bastard’ to England, where he found work as a British Rail ticket collector in London. They next confronted each other in the Old Bailey, over half a century later, where one was the principal prosecution witness, and the other charged with a fraction of the number of murders he was alleged to have committed. There was no physical evidence, just one man’s word against another, leaving the jury with a series of agonising dilemmas: Could any witness statement be trusted so long after the event? Was Andrusha a brutal killer, a hapless pawn or a scapegoat? And were his furious protests a sign of guilt or the justified anger of an innocent old man",
		author:'Mike Anderson',
		category:'Novels',
		cost: 17.99,
		count:1
	},
	{
		bookId:"book4",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/Gallant.jpg',
		product:'Gallant',
		description:"Everything casts a shadow. Even the world we live in. And as with every shadow, there is a place where it must touch. A seam, where the shadow meets its source",
		recommendations:"",
		story:"Olivia Prior has grown up in Merilance School for girls, and all she has of her past is her mother’s journal—which seems to unravel into madness. Then, a letter invites Olivia to come home—to Gallant. Yet when Olivia arrives, no one is expecting her. But Olivia is not about to leave the first place that feels like home, it doesn’t matter if her cousin Matthew is hostile or if she sees half-formed ghouls haunting the hallways. Olivia knows that Gallant is hiding secrets, and she is determined to uncover them. When she crosses a ruined wall at just the right moment, Olivia finds herself in a place that is Gallant—but not. The manor is crumbling, the ghouls are solid, and a mysterious figure rules over all. Now Olivia sees what has unraveled generations of her family, and where her father may have come from.",
		author:'V.E.Schwab ',
		category:'Novels',
		cost:17.99,
		count:1
	},
	{
		bookId:"book5",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/Bacon%20in%20Moscow.jpg',
		product:'Bacon in Moscow',
		description:"A rollicking cultural adventure... fascinating and true' Grayson Perry",
		recommendations:"This funny and personal memoir is the account of an audacious attempt by James Birch, a young British curator, to mount the ground-breaking retrospective of Francis Bacon's work at the newly refurbished Central House of Artists, Moscow in 1988.",
		story:"Side-lined by the British establishment, Birch found himself at the heart of a honey-trap and the focus for a picaresque cast of Soviet officials, attach�s and politicians under the forbidding eye of the KGB as he attempted to bring an unseen western cultural icon to Russia during the time of 'Glasnost', just before the fall of the Berlin Wall.Bacon in Moscow is the story of the evolution of an exhibition that was at the artistic and political heart of a sea of change that culminated with the fall of the USSR.'A rollicking cultural adventure before the fall of the Berlin Wall and the meteoric rise of contemporary art in the nineties' Grayson Perry",
		author:'James Birch ',
		category:'other',
		cost:17.99,
		count:1
	},
	{
		bookId:"book6",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/9780241519332.jpg',
		product:'The Lyrics',
		description:"An incredibly moving experience ... Hicks's summation of life gains greater spirituality as he goes on.' Scarlett Thomas, Independent on Sunday",
		recommendations: "",
		story:"",
		author:'Ian Rankin',
		category:'Novels',
		cost:20.00,
		count:1
	},
	{
		bookId:"book7",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/1.jpg',
		product:'Harry Potter and the Philosophers Stone',
		description:"Harry Potter thinks he is an ordinary boy - until he is rescued by an owl, taken to Hogwarts School of Witchcraft and Wizardry, learns to play Quidditch and does battle in a deadly duel. The Reason ... HARRY POTTER IS A WIZARD!",
		recommendations: "",
		story:"",
		author:'J. K. Rowling ',
		category:'Harry Potter',
		cost:7.92,
		count:1
	},
	{
		bookId:"book8",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/2.jpg',
		product:'Harry Potter and the Chamber of Secrets',
		description:"Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.",
		recommendations: "",
		story:"And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possible be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself",
		author:'J. K. Rowling',
		cost:8.92,
		category:'Harry Potter',
		count:1
	},
	{
		bookId:"book9",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/3.jpg',
		product:'Harry Potter and the Prisoner of Azkaban',
		description:"This spectacular souvenir folio comes loaded with full-color and black and white photos from the blockbuster Harry Potter film. Titles: Aunt Marge's Waltz",
		recommendations: "",
		story:"For use in schools and libraries only. During his third year at Hogwarts School for Witchcraft and Wizardry, Harry Potter must confront the devious and dangerous wizard responsible for his parents' deaths.",
		author:'J. K. Rowling',
		category:'Harry Potter',
		cost:8.99,
		count:1
	},
	{
		bookId:"book11",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/4.jpg',
		product:'Harry Potter and the Goblet of Fire',
		description:"",
		recommendations: "",
		story:"Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards.",
		author:'J. K. Rowling',
		category:'Harry Potter',
		cost:8.99,
		count:1
	},
	{
		bookId:"book12",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/5.jpg',
		product:'Harry Potter and the Order of the Phoenix',
		description:"There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?",
		recommendations: "",
		story:"Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop, As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice",
		author:'J. K. Rowling',
		category:'Harry Potter',
		cost:8.99,
		count:1
	},
	{
		bookId:"book13",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/6.jpg',
		product:'Harry Potter and the Half-Blood Prince',
		description:"The war against Voldemort is not going well; even Muggle governments are noticing. Ron scans the obituary pages of the Daily Prophet, looking for familiar names. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses.",
		recommendations: "",
		story:"As in all wars, life goes on. The Weasley twins expand their business. Sixth-year students learn to Apparate - and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are never straightforward, through Harry receives some extraordinary help from the mysterious Half-Blood Prince, So it's the home front that takes center stage in the multilayered sixth installment of the story of Harry Potter. Here at Hogwarts, Harry will search for the full and complete story of the boy who became Lord Voldemort - and thereby find what may be his only vulnerability",
		author:'J. K. Rowling',
		category:'Harry Potter',
		cost:8.99,
		count:1
	},
	{
		bookId:"book14",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/7.jpg',
		product:'Harry Potter and the Deathly Hallows',
		description:"",
		recommendations: "",
		story:"It's no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run. Professor Dumbledore has given them clues about what they need to do to defeat the dark wizard, Lord Voldemort, once and for all, but it's up to them to figure out what these hints and suggestions really mean. Their cross-country odyssey has them searching desperately for the answers, while evading capture or death at every turn. At the same time, their friendship, fortitude, and sense of right and wrong are tested in ways they never could have imagined. The ultimate battle between good and evil that closes out this final chapter of the epic series takes place where Harry's Wizarding life began: at Hogwarts. The satisfying conclusion offers shocking last-minute twists, incredible acts of courage, powerful new forms of magic, and the resolution of many mysteries. Above all, this intense, cathartic book serves as a clear statement of the message at the heart of the Harry Potter series: that choice matters much more than destiny, and that love will always triumph over death",
		author:'J. K. Rowling',
		category:'Harry Potter',
		cost:8.99,
		count:1
	},
	{
		bookId:"book15",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/9780751565362.jpg',
		product:'Harry Potter and the Cursed Child ',
		description:"",
		recommendations: "",
		story:"Harry Potter and the Cursed Child, Parts 1 & 2 and Harry Potter and the Philosopher's Stone 2 Books Bundle Collection. Description:- Harry Potter and the Cursed Child, Parts 1 & 2, Special Rehearsal Edition Script It was always difficult being Harry Potter and it isn't much easier now that he is an overworked employee of the Ministry of Magic, a husband and father of three school-age children. While Harry grapples with a past that refuses to stay where it belongs, his youngest son Albus must struggle with the weight of a family legacy he never wanted. As past and present fuse ominously, both father and son learn the uncomfortable truth: sometimes, darkness comes from unexpected places.'Harry Potter and the Philosopher's Stone: Illustrated Edition (Harry Potter Illustrated Editi) Prepare to be spellbound by Jim Kay's dazzling depiction of the wizarding world and much loved characters in this full-colour illustrated hardback edition of the nation's favourite children's book - Harry Potter and the Philosopher's Stone. Brimming with rich detail and humour that perfectly complements J.K. Rowling's timeless classic, Jim Kay's glorious illustrations will captivate fans and new readers alike. When a letter arrives for unhappy but ordinary Harry Potter, a decade-old secret is revealed to him that apparently he's the last to know. His parents were wizards, killed by a Dark Lord's curse when Harry was just a baby, and which he somehow survived. Leaving his unsympathetic aunt and uncle for Hogwarts School of Witchcraft and Wizardry, Harry stumbles upon a sinister mystery when he finds a three-headed dog guarding a room on the third floor. Then he hears of a missing stone with astonishing powers, which could be valuable, dangerous - or both. An incredible adventure is about to begin!",
		author:'J. K. Rowling',
		category:'Harry Potter',
		cost:8.99,
		count:1
	},
	{
		bookId:"book16",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/js.jpg',
		product:'Node.js Design Patterns',
		description:"Get the best out of Node.js by mastering a series of patterns and techniques to create modular, scalable, and efficient applications",
		recommendations:"About This Book Dive into the core patterns and components of Node.js in order to master your application's design Learn tricks, techniques, and best practices to solve common design and coding challenges Take a code-centric approach to using Node.js without friction Who This Book Is For",
		story:"If you're a JavaScript developer interested in a deeper understanding of how to create and design Node.js applications, this is the book for you. In this book, we will take you on a journey across various ideas and components, and the challenges you would commonly encounter while designing and developing software using the Node.js platform. You will also discover the 'Node.js way' of dealing with design and coding decisions.The book kicks off by exploring the fundamental principles and components that define the platform. It then shows you how to master asynchronous programming and how to design elegant and reusable components using well-known patterns and techniques. The book rounds off by teaching you the various approaches to scale, distribute, and integrate your Node.js application.",
		author:'Mario Casciaro',
		category:'js',
		cost:37.99,
		count:1
	},
	{
		bookId:"book17",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/js%2019.jpg',
		product:'You Don t Know JS Yet',
		description:"",
		recommendations: "",
		story:"",
		author:'Mario Casciaro',
    category:'-',
		cost:19.95,
		count:1
	},
	{
		bookId:"book18",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/Aditya%20Bhargava.jpg',
		product:'Grokking Algorithms',
		description:"An algorithm is nothing more than a step-by-step procedure for solving a problem. The algorithms you'll use most often as a programmer have already been discovered, tested, and proven. If you want to take a hard pass on Knuth's brilliant but impenetrable theories and the dense multi-page proofs you'll find in most textbooks, this is the book for you. This fully-illustrated and engaging guide makes it easy for you to learn how to use algorithms effectively in your own programs.",
		recommendations: "",
		story:"Grokking Algorithms is a disarming take on a core computer science topic. In it, you'll learn how to apply common algorithms to the practical problems you face in day-to-day life as a programmer. You'll start with problems like sorting and searching. As you build up your skills in thinking algorithmically, you'll tackle more complex concerns such as data compression or artificial intelligence. Whether you're writing business software, video games, mobile apps, or system utilities, you'll learn algorithmic techniques for solving problems that you thought were out of your grasp.Each carefully-presented example includes helpful diagrams and fully-annotated code samples in Python. By the end of this book, you will know some of the most widely applicable algorithms as well as how and when to use them",
		author:'Aditya Bhargava',
		category:'js',
		cost:37.99,
		count:1
	},
	{
		bookId:"book19",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/9781118531648.jpg',
		product:'JavaScript and JQuery',
		description:"This full-color book adopts a visual approach to teaching JavaScript & jQuery, showing you how to make web pages more interactive and interfaces more intuitive through the use of inspiring code examples, infographics, and photography. The content assumes no previous programming experience, other than knowing how to create a basic web page in HTML & CSS.",
		recommendations: "",
		story:"",
		author:'Jon Duckett',
		category:'js',
		cost:30.99,
		count:1
	},
	{
		bookId:"book20",
		photo:'https://raw.githubusercontent.com/wolk8396/test/main/homework17/Thich%20Nhat%20Hanh.jpg',
		product:'Silence: The Power of Quiet in a World Full of Noise',
		description:"We can spend a lot of time looking for happiness when the world right around us is full of wonder. But our hearts and minds are so full of noise that we can’t always hear the call of life and love. To hear that call and respond to it, we need silence",
		recommendations: "",
		story:"In his beautiful new book, Buddhist monk and Nobel Peace Prize nominee Thich Nhat Hanh explains how mindfulness is the practice that stops the noise inside. With gentle anecdotes, simple Buddhist wisdom and practical exercises, he shows us how to live mindfully so that all the internal chatter ceases and we are left with the eloquent sound of silence. Now, at last, we can answer the call of the beauty around us. Through silence, Thich Nhat Hanh reveals, we are free to hear, to see - and just be",
		author:'Thich Nhat Hanh',
		category:'other',
		cost:12.99,
		count:1
	},
	{
		bookId:"book21",
		photo:'https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FSea%20of%20Tranquility.jpg?alt=media&token=f6617d12-2770-41bb-bbc2-7e680b4217e9',
		product:'Sea of Tranquility',
		description:"NEW YORK TIMES BEST SELLER - The award-winning, best-selling author of Station Eleven and The Glass Hotel returns with a novel of art, time, love, and plague that takes the reader from Vancouver Island in 1912 to a dark colony on the moon five hundred years later, unfurling a story of humanity across centuries and space.One of Mandel's finest novels and one of her most satisfying forays into the arena of speculative fiction yet.",
		recommendations: "",
		story:"Edwin St. Andrew is eighteen years old when he crosses the Atlantic by steamship, exiled from polite society following an ill-conceived diatribe at a dinner party. He enters the forest, spellbound by the beauty of the Canadian wilderness, and suddenly hears the notes of a violin echoing in an airship terminal--an experience that shocks him to his core. Two centuries later a famous writer named Olive Llewellyn is on a book tour. She's traveling all over Earth, but her home is the second moon colony, a place of white stone, spired towers, and artificial beauty. Within the text of Olive's best-selling pandemic novel lies a strange passage: a man plays his violin for change in the echoing corridor of an airship terminal as the trees of a forest rise around him.When Gaspery-Jacques Roberts, a detective in the black-skied Night City, is hired to investigate an anomaly in the North American wilderness, he uncovers a series of lives upended: The exiled son of an earl driven to madness, a writer trapped far from home as a pandemic ravages Earth, and a childhood friend from the Night City who, like Gaspery himself, has glimpsed the chance to do something extraordinary that will disrupt the timeline of the universe.A virtuoso performance that is as human and tender as it is intellectually playful, Sea of Tranquility is a novel of time travel and metaphysics that precisely captures the reality of our current moment.",
		author:"Emily St John Mandel",
		category:'Science Fiction',
		cost:23.25,
		count:1
	},
	{
		bookId:"book22",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FLast%20Night%20in%20Montreal.jpg?alt=media&token=1d144482-2186-4cf9-8fb4-2499db8b5200",
		product:'Last Night in Montreal',
		description:"Lilia Albert has been leaving people behind for her entire life. She spends her childhood and adolescence traveling constantly and changing identities. In adulthood, she finds it impossible to stop. Haunted by an inability to remember her early childhood, she moves restlessly from city to city, abandoning lovers along with way, possibly still followed by a private detective who has pursued her for years. Then her latest lover follows her from New York to Montreal, determined to learn her secrets and make sure she s safe.",
		recommendations: "",
		story:"Last Night in Montreal is a story of love, amnesia, compulsive travel, the depths and the limits of family bonds, and the nature of obsession. In this extraordinary debut, Emily St. John Mandel casts a powerful spell that captures the reader in a gritty, youthful world charged with an atmosphere of mystery, promise and foreboding where small revelations continuously change our understanding of the truth and lead to desperate consequences. Mandel's characters will resonate with you long after the final page is turned.",
		author:"Emily St John Mandel",
		category:"Science Fiction",
		cost:14.83,
		count:1
	},
	{
		bookId:"book23",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20Singer's%20Gun.jpg?alt=media&token=193b0d28-bd48-4e1c-a67d-b7b75b47bd82",
		product:"The Singer's Gun",
		description:"",
		recommendations: "",
		story:"Everyone Anton Waker grew up with is corrupt. His parents deal in stolen goods and his first career is a partnership venture with his cousin Aria selling forged passports and social security cards to illegal aliens. Anton longs for a less questionable way of living in the world and by his late twenties has reinvented himself as a successful middle manager. Then a routine security check suggests that things are not quite what they appear. And Aria begins blackmailing him to do one last job for her. But the seemingly simple job proves to have profound and unexpected repercussions",
		author:"Emily St John Mandel",
		category:"Science Fiction",
		cost:14.83,
		count:1
	},
	{
		bookId:"book24",
		photo:'https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FDaisy%20Jones%20%26%20the%20Six.jpg?alt=media&token=23b6a858-faab-4c50-bf83-4e0f1e617b43',
		product:"Daisy Jones & The Six",
		description:"A gripping novel about the whirlwind rise of an iconic 1970s rock group and their beautiful lead singer, revealing the mystery behind their infamous break up.",
		recommendations: "",
		story:"Daisy is a girl coming of age in L.A. in the late sixties, sneaking into clubs on the Sunset Strip, sleeping with rock stars, and dreaming of singing at the Whisky a Go-Go. The sex and drugs are thrilling, but it’s the rock and roll she loves most. By the time she’s twenty, her voice is getting noticed, and she has the kind of heedless beauty that makes people do crazy things.Another band getting noticed is The Six, led by the brooding Billy Dunne. On the eve of their first tour, his girlfriend Camila finds out she’s pregnant, and with the pressure of impending fatherhood and fame, Billy goes a little wild on the road.Daisy and Billy cross paths when a producer realizes the key to supercharged success is to put the two together. What happens next will become the stuff of legend.",
		author:"Taylor Jenkins Reid ",
		category:"fantasy",
		cost:15.83,
		count:1
	},
	{
		bookId:"book25",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FOne%20True%20Loves.jpg?alt=media&token=08feda07-a3d7-47f8-aeb5-5efeb23c3752",
		product:"One True Loves",
		description:"In her twenties, Emma Blair marries her high school sweetheart, Jesse. They build a life for themselves, far away from the expectations of their parents and the people of their hometown in Massachusetts. They travel the world together, living life to the fullest and seizing every opportunity for adventure.",
		recommendations: "",
		story:"On their first wedding anniversary, Jesse is on a helicopter over the Pacific when it goes missing. Just like that, Jesse is gone forever.Emma quits her job and moves home in an effort to put her life back together. Years later, now in her thirties, Emma runs into an old friend, Sam, and finds herself falling in love again. When Emma and Sam get engaged, it feels like Emma’s second chance at happiness.That is, until Jesse is found. He’s alive, and he’s been trying all these years to come home to her. With a husband and a fiancé, Emma has to now figure out who she is and what she wants, while trying to protect the ones she loves.",
		author:"Taylor Jenkins Reid ",
		category:"fantasy",
		cost:15.83,
		count:1
	},
	{
		bookId:"book26",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FEvidence%20of%20the%20Affair.jpg?alt=media&token=b1e2b54e-3f69-441b-9824-86b50c84d358",
		product:"Evidence of the Affair",
		description:"A desperate young woman in Southern California sits down to write a letter to a man she’s never met—a choice that will forever change both their lives.",
		recommendations: "",
		story:"",
		author:"Taylor Jenkins Reid ",
		category:"fantasy",
		cost:11.83,
		count:1
	},
	{
		bookId:"book27",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20Shining.jpg?alt=media&token=01b555a8-8945-4d6b-abfb-123ff34491b2",
		product:"The Shining",
		description:"Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:13.83,
		count:1
	},
	{
		bookId:"book28",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20Gunslinger.jpg?alt=media&token=e8e6db65-f388-4764-a4c9-6692605a9ac5",
		product:"The Gunslinger",
		description:"In the first book of this brilliant series, Stephen King introduces readers to one of his most enigmatic heroes, Roland of Gilead, The Last Gunslinger. He is a haunting figure, a loner on a spellbinding journey into good and evil. In his desolate world, which frighteningly mirrors our own, Roland pursues The Man in Black, encounters an alluring woman named Alice, and begins a friendship with the Kid from Earth called Jake. Both grippingly realistic and eerily dreamlike, The Gunslinger leaves readers eagerly awaiting the next chapter.",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:15.83,
		count:1
	},
	{
		bookId:"book29",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FWizard%20and%20Glass.jpg?alt=media&token=38c325c6-89f9-4db0-ab92-2bdb660b1dee",
		product:"Wizard and Glass",
		description:"Roland, Eddie, Susannah, Jake, and Jake’s pet bumbler survive Blaine the Mono’s final crash, only to find themselves stranded in an alternate version of Topeka, Kansas, one that has been ravaged by the superflu virus. While following the deserted I-70 toward a distant glass palace, they hear the atonal squalling of a thinny, a place where the fabric of existence has almost entirely worn away. While camping near the edge of the thinny, Roland tells his ka-tet a story about another thinny, one that he encountered when he was little more than a boy. Over the course of one long magical night, Roland transports us to the Mid-World of long-ago and a seaside town called Hambry, where Roland fell in love with a girl named Susan Delgado, and where he and his old tet-mates Alain and Cuthbert battled the forces of John Farson, the harrier who—with a little help from a seeing sphere called Maerlyn’s Grapefruit—ignited Mid-World’s final war",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:14.83,
		count:1
	},
	{
		bookId:"book30",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FWolves%20of%20the%20Calla.jpg?alt=media&token=92492970-b71f-41b4-a005-fee1197652c7",
		product:"Wolves of the Calla",
		description:"Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:11.23,
		count:1
	},
	{
		bookId:"book31",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20Stand.jpg?alt=media&token=f8c1c2a8-f5d3-46f4-9af4-01d62c2b6048",
		product:"The Stand",
		description:"When a man escapes from a biological testing facility, he sets in motion a deadly domino effect, spreading a mutated strain of the flu that will wipe out 99 percent of humanity within a few weeks. The survivors who remain are scared, bewildered, and in need of a leader. Two emerge–Mother Abagail, the benevolent 108-year-old woman who urges them to build a peaceful community in Boulder, Colorado; and Randall Flagg, the nefarious “Dark Man,” who delights in chaos and violence. As the dark man and the peaceful woman gather power, the survivors will have to choose between them–and ultimately decide the fate of all humanity",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:9.83,
		count:1
	},
	{
		bookId:"book32",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FMisery.jpg?alt=media&token=3a05a247-ced3-4d43-bccd-9a8fd75d71ef",
		product:"Misery",
		description:"Paul Sheldon. He's a bestselling novelist who has finally met his biggest fan. Her name is Annie Wilkes and she is more than a rabid reader - she is Paul's nurse, tending his shattered body after an automobile accident. But she is also his captor, keeping him prisoner in her isolated house",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:9.83,
		count:1
	},
	{
		bookId:"book33",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2Fcarrie.jpg?alt=media&token=44d2be80-1326-47ae-8e87-6e5a122133fe",
		product:"Carrie",
		description:"A modern classic, Carrie introduced a distinctive new voice in American fiction -- Stephen King. The story of misunderstood high school girl Carrie White, her extraordinary telekinetic powers, and her violent rampage of revenge, remains one of the most barrier-breaking and shocking novels of all time.",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:15,
		count:1
	},
	{
		bookId:"book34",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20Waste%20Lands.jpg?alt=media&token=8707fa56-f31f-4619-b3ae-403aba903ae9",
		product:"The Waste Lands",
		description:"Several months have passed, and Roland’s two new tet-mates have become proficient gunslingers. Eddie Dean has given up heroin, and Odetta’s two selves have joined, becoming the stronger and more balanced personality of Susannah Dean. But while battling The Pusher in 1977 New York, Roland altered ka by saving the life of Jake Chambers, a boy who—in Roland’s where and when—has already died. Now Roland and Jake exist in different worlds, but they are joined by the same madness: the paradox of double memories. Roland, Susannah, and Eddie must draw Jake into Mid-World then follow the Path of the Beam all the way to the Dark Tower. But nothing is easy in Mid-World. Along the way our tet stumbles into the ruined city of Lud, and are caught between the warring gangs of the Pubes and the Grays. The only way out of Lud is to wake Blaine the Mono, an insane train that has a passion for riddling, and for suicidal journeys",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:9.83,
		count:1
	},
	{
		bookId:"book35",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2Fcell.jpg?alt=media&token=2dd47584-18bf-4d35-9eeb-eb787ccf06bf",
		product:"Cell",
		description:"Graphic artist Clay Riddell was in the heart of Boston on that brilliant autumn afternoon when hell was unleashed before his eyes. Without warning, carnage and chaos reigned. Ordinary people fell victim to the basest, most animalistic destruction.",
		recommendations: "",
		story:"",
		author:"Stephen King",
		category:"Science Fiction",
		cost:9.83,
		count:1
	},
	{
		bookId:"book36",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FHidden%20Pictures.jpg?alt=media&token=6a20623a-c1f6-4b64-a5f1-6d89734d5cf1",
		product:"Hidden Pictures",
		description:"Fresh out of rehab, Mallory Quinn takes a job in the affluent suburb of Spring Brook, New Jersey as a babysitter for Ted and Caroline Maxwell. She is to look after their five-year-old son, Teddy Mallory immediately loves this new job. She lives in the Maxwell’s pool house, goes out for nightly runs, and has the stability she craves. And she sincerely bonds with Teddy, a sweet, shy boy who is never without his sketchbook and pencil. His drawings are the usual fare: trees, rabbits, balloons. But one day, he draws something different: a man in a forest, dragging a woman’s lifeless body.",
		recommendations: "",
		story:"",
		author:"Jason Rekulak",
		category:"Crime",
		cost:14.83,
		count:1
	},
	{
		bookId:"book37",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20X-Files.jpg?alt=media&token=35f93b4c-330e-42a1-8245-392bc03b5e25",
		product:"The X-Files: Earth Children are Weird",
		description:"",
		recommendations: "One the most beloved TV shows of all time is now a sweet, silly, sci-fi bedtime story! In The X Files: Earth Children Are Weird, best pals Dana (Scully) and Fox (Mulder) have pitched a tent in the backyard for a sleepover. But the night is full of strange sounds, lights, and shadows. Surely there’s a rational, scientific explanation for everything . . . or is there? With beautiful illustrations of pint-sized Dana and Fox, this humorous and not-scary-at-all story will introduce the cult TV show to an entire new generation of fans.",
		story:"",
		author:"Jason Rekulak",
		category:"Crime",
		cost:14.83,
		count:1
	},
	{
		bookId:"book38",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FBuffy%20contre%20les%20vampires.jpg?alt=media&token=0c30a92c-6f83-47ea-a85b-58b384a6708d",
		product:"Buffy contre les vampires",
		description:"Cet album plonge le lecteur dans l'enfance de Buffy et ses amis, en lutte contre les vampires.",
		recommendations: "",
		story:"",
		author:"Jason Rekulak",
		category:"Illustrator",
		cost:14.83,
		count:1
	},
	{
		bookId:"book39",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FBack%20to%20the%20Future.jpg?alt=media&token=c3078b44-faaa-4c52-a435-c151caba3599",
		product:"Back to the Future",
		description:"One the most beloved TV shows of all time is now a sweet, silly, sci-fi bedtime story! In The X Files: Earth Children Are Weird, best pals Dana (Scully) and Fox (Mulder) have pitched a tent in the backyard for a sleepover. But the night is full of strange sounds, lights, and shadows. Surely there’s a rational, scientific explanation for everything . . . or is there? With beautiful illustrations of pint-sized Dana and Fox, this humorous and not-scary-at-all story will introduce the cult TV show to an entire new generation of fans.",
		recommendations: "",
		story:"",
		author:"Jason Rekulak",
		category:"Illustrator",
		cost:14.83,
		count:1
	},
	{
		bookId:"book40",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FHome%20Alone.jpg?alt=media&token=58df5d73-e634-4afe-a371-786ce58efa11",
		product:"Home Alone: The Classic Illustrated Storybook",
		description:"Home Alone arrived in theaters 25 years ago, and it remains the #1 highest-grossing live-action comedy film of all time. Now, illustrator Kim Smith has reimagined the story as a classic Christmas fable—complete with bumbling burglars, brilliant booby-traps, and a little boy named Kevin who’s forced to fend for himself. Through a series of comic adventures, Kevin learns lessons about responsibility and the importance of family. With an amusing read-aloud story and enchanting, immersive illustrations, this charming adaptation can be enjoyed year after year alongside The Polar Express, How the Grinch Stole Christmas, and other Christmas storybook classics",
		recommendations: "",
		story:"",
		author:"Jason Rekulak",
		category:"Illustrator",
		cost:14.83,
		count:1
	},
	{
		bookId:"book41",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2Fblock.jpg?alt=media&token=7cd5d268-7775-40ac-a5ca-d7bcfb94f73b",
		product:"The Writer's Block: 786 Ideas To Jump-start Your Imagination",
		description:"Anxious to write that Great American Novel but don't know where to begin? Help is on the way with our Writer's Block! This guide to beating writer's block comes packaged in the shape of an actual block: 3' x 3'x 3', with 672 pages and more than 200 photographs throughout. Next time you're stuck, just flip open The Writer's Block to any page to find an idea or exercise that will jump-start your imagination. Many of these assignments come straight from the creative writing classes of celebrated novelists like Ethan Canin, Richard Price, Toni Morrison, and Kurt Vonnegut: Joyce Carol Oates explains how she uses running to destroy writer's block. Elmore Leonard describes how he often finds ideas just by reading the newspaper",
		recommendations: "",
		story:"",
		author:"Jason Rekulak",
		category:"Crime",
		cost:14.83,
		count:1
	},
	{
		bookId:"book42",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FLet's%20Paint%20the%20'90s.jpg?alt=media&token=5a7046f3-78e4-41ea-b1c4-c1a5f593df23",
		product:"Let's Paint the '90s",
		description:"The glory of grunge! The beauty of Baywatch! The awesome Arsenio Hall! Now all of your favorite ’90s moments and personalities have been assembled in a single book—and you can bring them to life with the enclosed paint set and brush. Let’s paint Bill Clinton! Let’s paint Vanilla Ice! Let’s paint the ’90s!",
		recommendations: "",
		story:"",
		author:"Jason Rekulak",
		category:"Crime",
		cost:14.83,
		count:1
	},
	{
		bookId:"book43",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FClever%20Girl.jpg?alt=media&token=ecc926db-40d4-427f-866e-0771d66c6c2a",
		product:"Clever Girl",
		description:"Clever Girl is an indelible story of one woman’s life, unfolded in a series of beautifully sculpted episodes that illuminate an era, moving from the 1960s to today, from one of Britain’s leading literary lights—Tessa Hadley—the author of the New York Times Notable Books Married Love and The London Train.",
		recommendations:"",
		story:"",
		author:"Tessa Hadley",
		category:"Historical",
		cost:14.99,
		count:1
	},
	{
		bookId:"book44",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20London%20Train.jpg?alt=media&token=0beffe80-4b22-4e19-8573-c3bd8f19ecaa",
		product:"The London Train",
		description:"Two lives, stretched between two cities, converge in a chance meeting with immediate and far-reaching consequences in this compelling, sophisticated tale from acclaimed New Yorker writer Tessa Hadley, author of Accidents in the Home and The Master Bedroom. As father struggles to reestablish a relationship with his estranged daughter in London, surrendering himself to an underground life of illegal squats and counterculture friendships, a wife decides she must flee her suffocating marriage to return to Wales, where in Cardiff she may rediscover the passions that once fueled her life. Embracing change and facing loss, in a story evocative of Alice Munro’s Runaway and Julia Glass’ I See You Everywhere, Hadley’s powerful characters illuminate the furthest reaches of love, hope, and determination.",
		recommendations:"",
		story:"",
		author:"Tessa Hadley",
		category:"Historical",
		cost:10.99,
		count:1
	},
	{
		bookId:"book45",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FLate%20in%20the%20Day.jpg?alt=media&token=ae5de674-af19-4ce4-bf6d-3382965ae6fd",
		product:"Late in the Day",
		description:"Alexandr and Christine and Zachary and Lydia have been friends since they first met in their twenties. Thirty years later, Alex and Christine are spending a leisurely summer’s evening at home when they receive a call from a distraught Lydia: she is at the hospital. Zach is dead.",
		recommendations:"",
		story:"",
		author:"Tessa Hadley",
		category:"Historical",
		cost:17.99,
		count:1
	},
	{
		bookId:"book46",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FThe%20Past.jpg?alt=media&token=aced5442-ed51-4f02-b7a5-eec36ec9176d",
		product:"The Past",
		description:"A mesmerizing novel about family and the modern world encroaching upon the old, from one of Britain's finest contemporary novelists.",
		recommendations:"",
		story:"",
		author:"Tessa Hadley",
		category:"Novels",
		cost:11.99,
		count:1
	},
	{
		bookId:"book47",
		photo:"https://firebasestorage.googleapis.com/v0/b/bookstore-67dde.appspot.com/o/booksPhoto%2FV.E.%20Schwab's%20ExtraOrdinary.jpg?alt=media&token=83c3cb90-5663-40e8-bf6c-6944ad228c0f",
		product:"V.E. Schwab's ExtraOrdinary",
		description:"",
		recommendations:"",
		story:"Set in the years between Vicious and Vengeful, ExtraOrdinary follows a teenage girl named Charlotte Tills who survives a bus crash and becomes EO – ExtraOrdinary – gaining the ability to see people’s deaths in reflective surfaces.",
		author:"V.E. Schwab",
		category:"Novels",
		cost:10.99,
		count:1
	}
];
